-- Idempotent seed. Cascading FKs clean up shops + reps when the partner row goes.
-- UUIDs are generated by Postgres (gen_random_uuid()); only stable identifiers
-- (slug, qr_token) are hardcoded. Never hand-craft fake UUIDs here — Postgres
-- uuid columns accept any 32-hex string, but Zod's z.string().uuid() enforces
-- RFC 4122 strict validation, so hand-crafted values cause 400s at the API.

delete from partners where slug = 'ihpo';

with new_partner as (
  insert into partners (slug, name, primary_color, accent_color, flow_preset, iban_behavior, locales_enabled, default_locale)
  values (
    'ihpo',
    'IHPO',
    '#E53935',
    '#FFFFFF',
    'simple',
    'deferred',
    array['nl','fr'],
    'fr'
  )
  returning id
),
brussels as (
  insert into shops (partner_id, name, address, city, zip, qr_token)
  select id, 'IHPO Brussels Central', 'Rue Royale 1', 'Brussels', '1000', 'demo-shop-brussels'
  from new_partner
  returning id
),
antwerp as (
  insert into shops (partner_id, name, address, city, zip, qr_token)
  select id, 'IHPO Antwerp Central', 'Meir 42', 'Antwerp', '2000', 'demo-shop-antwerp'
  from new_partner
  returning id
),
liege as (
  insert into shops (partner_id, name, address, city, zip, qr_token)
  select id, 'IHPO Liège Downtown', 'Rue de la Régence 10', 'Liège', '4000', 'demo-shop-liege'
  from new_partner
  returning id
)
insert into sales_reps (shop_id, display_name, email)
select id, 'Marie Dupont',  'marie@ihpo.example' from brussels
union all
select id, 'Jean Martin',   'jean@ihpo.example'  from brussels
union all
select id, 'Lotte Jansen',  'lotte@ihpo.example' from antwerp;
