-- Idempotent seed. Cascading FKs clean up shops + reps when the partner row goes.
-- UUIDs are generated by Postgres (gen_random_uuid()); only stable identifiers
-- (slug, qr_token) are hardcoded. Never hand-craft fake UUIDs here — Postgres
-- uuid columns accept any 32-hex string, but Zod's z.string().uuid() enforces
-- RFC 4122 strict validation, so hand-crafted values cause 400s at the API.

-- ── CMS: june_admin dev account ─────────────────────────────────────────────
-- For LOCAL dev (`supabase db reset`): direct auth.users insert works because
-- the local Auth container accepts it.
--
-- For CLOUD (june-onboarding-dev and any future env): DO NOT use direct SQL.
-- Direct inserts into auth.users on cloud projects miss internal Supabase Auth
-- fields (instance_id, identity rows, etc.) and cause "Database error finding
-- user" on sign-in. Instead, run once via the Admin Auth API:
--
--   curl -s -X POST "${NEXT_PUBLIC_SUPABASE_URL}/auth/v1/admin/users" \
--     -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
--     -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
--     -H "Content-Type: application/json" \
--     -d '{"email":"georgeslieben@gmail.com","email_confirm":true}'
--
-- Then insert into public.profiles with the UUID returned from that call.
-- See docs/admin-provisioning.md (or this comment) for the one-time setup script.
--
-- profiles INSERT is service_role-only per RLS; inserting here directly works
-- because seed SQL runs as the superuser, bypassing RLS.

-- Local-only: direct auth.users insert (no-op on cloud since Admin API is used there)
insert into auth.users (
  id, instance_id, email, encrypted_password,
  email_confirmed_at, role, aud, created_at, updated_at,
  raw_app_meta_data, raw_user_meta_data
)
select
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'georgeslieben@gmail.com',
  crypt('unused-magic-link-only', gen_salt('bf')),
  now(), 'authenticated', 'authenticated', now(), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"email_verified":true}'::jsonb
where not exists (
  select 1 from auth.users where email = 'georgeslieben@gmail.com'
);

insert into public.profiles (id, email, role, partner_id)
select id, 'georgeslieben@gmail.com', 'june_admin', null
from auth.users where email = 'georgeslieben@gmail.com'
on conflict (id) do nothing;

-- ── Partner: IHPO ────────────────────────────────────────────────────────────
-- ON CONFLICT DO UPDATE makes this idempotent across resets and cloud manual runs.
-- New columns (content_status, trust_badge_i18n, privacy_url_i18n, color variants)
-- are included here so the IHPO row is always fully populated after seeding.

with upserted_partner as (
  insert into partners (
    slug, name, primary_color, accent_color,
    flow_preset, iban_behavior, locales_enabled, default_locale,
    content_status, trust_badge_i18n, privacy_url_i18n
  )
  values (
    'ihpo',
    'IHPO',
    '#E53935',
    '#FFFFFF',
    'simple',
    'deferred',
    array['nl','fr'],
    'fr',
    'draft',
    '{"fr":"Certifié partenaire June","nl":"Gecertificeerd June-partner"}'::jsonb,
    '{"fr":"https://ihpo.be/confidentialite","nl":"https://ihpo.be/privacy"}'::jsonb
  )
  on conflict (slug) do update set
    name               = excluded.name,
    primary_color      = excluded.primary_color,
    accent_color       = excluded.accent_color,
    flow_preset        = excluded.flow_preset,
    iban_behavior      = excluded.iban_behavior,
    locales_enabled    = excluded.locales_enabled,
    default_locale     = excluded.default_locale,
    trust_badge_i18n   = excluded.trust_badge_i18n,
    privacy_url_i18n   = excluded.privacy_url_i18n
  returning id
),
new_partner as (
  -- Re-select so CTE chain works whether this was an insert or update.
  select id from upserted_partner
),
brussels as (
  insert into shops (partner_id, name, address, city, zip, qr_token)
  select id, 'IHPO Brussels Central', 'Rue Royale 1', 'Brussels', '1000', 'demo-shop-brussels'
  from new_partner
  on conflict (qr_token) do nothing
  returning id
),
antwerp as (
  insert into shops (partner_id, name, address, city, zip, qr_token)
  select id, 'IHPO Antwerp Central', 'Meir 42', 'Antwerp', '2000', 'demo-shop-antwerp'
  from new_partner
  on conflict (qr_token) do nothing
  returning id
),
liege as (
  insert into shops (partner_id, name, address, city, zip, qr_token)
  select id, 'IHPO Liège Downtown', 'Rue de la Régence 10', 'Liège', '4000', 'demo-shop-liege'
  from new_partner
  on conflict (qr_token) do nothing
  returning id
)
insert into sales_reps (shop_id, display_name, email)
select b.id, 'Marie Dupont', 'marie@ihpo.example'
from brussels b where not exists (select 1 from sales_reps where email = 'marie@ihpo.example');

insert into sales_reps (shop_id, display_name, email)
select b.id, 'Jean Martin', 'jean@ihpo.example'
from brussels b where not exists (select 1 from sales_reps where email = 'jean@ihpo.example');

insert into sales_reps (shop_id, display_name, email)
select a.id, 'Lotte Jansen', 'lotte@ihpo.example'
from antwerp a where not exists (select 1 from sales_reps where email = 'lotte@ihpo.example');
