import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { createServiceClient } from '@june/db';

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: partnerId } = await params;
  const supabase = createServiceClient();

  const { data: shops, error } = await supabase
    .from('shops')
    .select('id, name, address, city, zip, qr_token, active, created_at, partner_id')
    .eq('partner_id', partnerId)
    .order('name');

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  // Attach rep counts in one extra query
  const shopIds = (shops ?? []).map((s) => s.id);
  let repCounts: Record<string, number> = {};

  if (shopIds.length > 0) {
    const { data: reps } = await supabase
      .from('sales_reps')
      .select('shop_id')
      .in('shop_id', shopIds)
      .eq('active', true);

    for (const rep of reps ?? []) {
      repCounts[rep.shop_id] = (repCounts[rep.shop_id] ?? 0) + 1;
    }
  }

  const result = (shops ?? []).map((s) => ({
    ...s,
    rep_count: repCounts[s.id] ?? 0,
  }));

  return NextResponse.json(result);
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: partnerId } = await params;
  const body = await request.json();

  const { name, address, city, zip, active = true } = body;

  if (!name?.trim()) {
    return NextResponse.json({ error: 'name is required' }, { status: 400 });
  }

  const supabase = createServiceClient();

  // qr_token is auto-generated by the DB default (encode(gen_random_bytes(9), 'base64'))
  const { data, error } = await supabase
    .from('shops')
    .insert({ partner_id: partnerId, name: name.trim(), address, city, zip, active })
    .select()
    .single();

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  return NextResponse.json(data, { status: 201 });
}
